#!/bin/bash

install_neo4j_gpg() {
    echo "Install Neo4j repository GPG key"
    wget --quiet -P /tmp http://debian.neo4j.org/neotechnology.gpg.key
    sudo rpm --import /tmp/neotechnology.gpg.key
}

install_neo4j() {
    echo "Install Neo4j"
    sudo yum install -y neo4j
    echo "Set Java 8 to default"
    sudo /usr/sbin/alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
}

start_on_boot() {
    echo "Configure to start Neo4j at startup"
    sudo chkconfig neo4j on
}

main() {
    install_neo4j_gpg
    install_neo4j
    start_on_boot
}

main
